name: django_test
channels:
  - defaults
  - conda-forge
dependencies:
  - django=2.2.1=*
  - django-widget-tweaks
  - pip=19.2.2=*
  - python=3.7.4=*
  - jupyter
  - matplotlib
  - numpy
  - requests
  - nb_conda
  - rise
  - sqlparse
  - tensorflow
  - pandas
  - scikit-learn
  - scipy
  - pip:
    - torch
    - pygame
    - ipywidgets
    - jupyter_contrib_nbextensions